import type{Transaction}from'./data';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
const esc=(s:any)=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]!));
export function monthlyReportHtml(tx:Transaction[],year:number,month:number,budget:number){
 const inc=tx.filter(x=>x.kind==='income').reduce((s,x)=>s+ +x.amount,0),exp=tx.filter(x=>x.kind==='expense').reduce((s,x)=>s+ +x.amount,0),bal=inc-exp,rate=inc?Math.max(0,bal)/inc*100:0;
 const groups=['Home Expenses','Personal','Credit Card / Debt','Everyday / Misc'];
 const groupRows=groups.map(g=>`<tr><td>${esc(g)}</td><td>${money(tx.filter(x=>x.kind==='expense'&&x.group_name===g).reduce((s,x)=>s+ +x.amount,0))}</td></tr>`).join('');
 const rows=tx.filter(x=>x.kind==='expense').map(x=>`<tr><td>${esc(x.occurred_on)}</td><td>${esc(x.name)}</td><td>${esc(x.category||x.group_name)}</td><td>${esc(x.status)}</td><td>${money(+x.amount)}</td></tr>`).join('');
 return `<!doctype html><meta charset=utf-8><title>Monthly Financial Report</title><style>body{font:14px system-ui;padding:32px;color:#173047}h1{margin:0}.k{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:22px 0}.c{border:1px solid #ccdbe3;border-radius:10px;padding:12px}table{width:100%;border-collapse:collapse;margin:14px 0}th,td{padding:8px;border-bottom:1px solid #dde6eb;text-align:left}@media print{body{padding:0}}</style><h1>My Home Finance</h1><p>Monthly Financial Report — ${month}/${year}</p><div class=k><div class=c>Income<br><b>${money(inc)}</b></div><div class=c>Expenses<br><b>${money(exp)}</b></div><div class=c>Remaining<br><b>${money(bal)}</b></div><div class=c>Savings<br><b>${money(Math.max(0,bal))}</b></div><div class=c>Savings Rate<br><b>${rate.toFixed(1)}%</b></div><div class=c>Budget vs Actual<br><b>${budget?money(budget-exp)+' remaining':'Not Set'}</b></div></div><h2>Expense Groups</h2><table>${groupRows}</table><h2>Detailed Expenses</h2><table><tr><th>Date</th><th>Expense</th><th>Category</th><th>Status</th><th>Amount</th></tr>${rows||'<tr><td colspan=5>No expenses</td></tr>'}</table>`;
}
export function yearlyReportHtml(tx:Transaction[],year:number){
 let ai=0,ae=0;const rows=Array.from({length:12},(_,i)=>{const m=tx.filter(x=>new Date(x.occurred_on+'T00:00:00').getMonth()===i),inc=m.filter(x=>x.kind==='income').reduce((s,x)=>s+ +x.amount,0),exp=m.filter(x=>x.kind==='expense').reduce((s,x)=>s+ +x.amount,0);ai+=inc;ae+=exp;return `<tr><td>${new Date(2000,i).toLocaleString('en',{month:'long'})}</td><td>${money(inc)}</td><td>${money(exp)}</td><td>${money(inc-exp)}</td></tr>`}).join('');
 const bal=ai-ae;return `<!doctype html><meta charset=utf-8><title>Yearly Financial Report</title><style>body{font:14px system-ui;padding:32px;color:#173047}table{width:100%;border-collapse:collapse}th,td{padding:9px;border-bottom:1px solid #dde6eb;text-align:left}.k{display:flex;gap:14px;margin:20px 0}.k div{border:1px solid #ccdbe3;border-radius:10px;padding:12px;flex:1}@media print{body{padding:0}}</style><h1>My Home Finance — ${year} Closing Report</h1><div class=k><div>Annual Income<br><b>${money(ai)}</b></div><div>Annual Expenses<br><b>${money(ae)}</b></div><div>Net Balance<br><b>${money(bal)}</b></div><div>Total Savings<br><b>${money(Math.max(0,bal))}</b></div></div><table><tr><th>Month</th><th>Income</th><th>Expenses</th><th>Balance</th></tr>${rows}</table><p>No individual transaction detail is included in the yearly closing report.</p>`;
}
export function printHtml(html:string){const w=window.open('','_blank');if(!w)throw new Error('Popup blocked');w.document.write(html);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
