import{useCallback,useEffect,useMemo,useState}from'react';import{deleteTransaction,exportBackup,getBudget,listGoals,listTransactions,listYear,range,setBudget,saveGoal,subscribe,Transaction,Goal}from'../lib/data';import TransactionModal from'./TransactionModal';import RestoreBackup from'./RestoreBackup';import{monthlyReportHtml,yearlyReportHtml,printHtml}from'../lib/reports';
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n);
type Page='Dashboard'|'Expenses'|'Income & Savings'|'Reports'|'Settings';
export default function FinanceApp(){const now=new Date(),[page,setPage]=useState<Page>('Dashboard'),[year,setYear]=useState(now.getFullYear()),[month,setMonth]=useState(now.getMonth()+1),[tx,setTx]=useState<Transaction[]>([]),[budget,setB]=useState(0),[goals,setGoals]=useState<Goal[]>([]),[modal,setModal]=useState<null|'income'|'expense'>(null),[edit,setEdit]=useState<Transaction|undefined>(),[dark,setDark]=useState(localStorage.getItem('mhf-theme')==='dark');
const load=useCallback(async()=>{const[s,e]=range(year,month);const[a,b,g]=await Promise.all([listTransactions(s,e),getBudget(s),listGoals()]);setTx((a.data||[])as Transaction[]);setB(Number(b.data?.amount||0));setGoals((g.data||[])as Goal[])},[year,month]);useEffect(()=>{load();return subscribe(load)},[load]);useEffect(()=>{document.body.classList.toggle('dark',dark);localStorage.setItem('mhf-theme',dark?'dark':'light')},[dark]);
const t=useMemo(()=>{let income=0,expenses=0,unpaid=0;tx.forEach(x=>{if(x.kind==='income')income+=+x.amount;else{expenses+=+x.amount;if(x.status==='unpaid')unpaid+=+x.amount}});const balance=income-expenses;return{income,expenses,balance,savings:Math.max(0,balance),rate:income?Math.max(0,balance)/income*100:0,unpaid}},[tx]);
const nav=(p:Page)=><button className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>;
function open(k:'income'|'expense',x?:Transaction){setEdit(x);setModal(k)} async function del(x:Transaction){if(confirm(`Delete ${x.name} (${money(+x.amount)})?`)){await deleteTransaction(x.id);load()}}
function rows(list:Transaction[]){return list.length?<div className="rows">{list.map(x=><div className="row" key={x.id}><span><b>{x.name}</b><small>{x.occurred_on} • {x.category||x.group_name||x.kind} • {x.status}</small></span><strong>{x.kind==='expense'?'-':'+'}{money(+x.amount)}</strong><div className="actions"><button onClick={()=>open(x.kind,x)}>Edit</button><button onClick={()=>del(x)}>Delete</button></div></div>)}</div>:<div className="empty"><b>No data yet</b><span>Add your real financial data when ready.</span></div>}
async function backup(){const data=await exportBackup(),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`my-home-finance-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
const calendar=Array.from({length:new Date(year,month,0).getDate()},(_,i)=>i+1);return <div className="shell"><aside><div><h2>⌂ My Home Finance</h2><small>Plan Today. A Better Tomorrow.</small></div><nav>{nav('Dashboard')}{nav('Expenses')}{nav('Income & Savings')}{nav('Reports')}{nav('Settings')}</nav></aside><main className="workspace"><header className="top"><div><h1>{page}</h1><p>Manage today. Live better tomorrow.</p></div><div className="period"><select value={month} onChange={e=>setMonth(+e.target.value)}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{new Date(2000,i).toLocaleString('en',{month:'long'})}</option>)}</select><select value={year} onChange={e=>setYear(+e.target.value)}>{Array.from({length:27},(_,i)=><option value={2024+i} key={i}>{2024+i}</option>)}</select></div></header>
{page==='Dashboard'&&<><section className="hero"><div><small>MONTHLY FINANCIAL HEALTH</small><h2>{money(t.balance)}</h2><p>Remaining Balance</p></div><span>{t.rate.toFixed(1)}% savings rate</span></section><section className="metrics"><article><small>Monthly Income</small><b>{money(t.income)}</b></article><article><small>Total Expenses</small><b>{money(t.expenses)}</b></article><article className="primary"><small>Remaining Balance</small><b>{money(t.balance)}</b></article><article><small>Monthly Savings</small><b>{money(t.savings)}</b></article></section><section className="twocol"><div className="card"><header><h2>Recent Transactions</h2><button onClick={()=>open('expense')}>+ Add Expense</button></header>{rows(tx.slice(0,8))}</div><div className="card"><h2>Upcoming / Unpaid</h2><b className="big">{money(t.unpaid)}</b>{rows(tx.filter(x=>x.kind==='expense'&&x.status==='unpaid').slice(0,5))}</div></section><section className="card"><header><h2>Budget</h2><button onClick={async()=>{const v=prompt('Monthly budget',String(budget||''));if(v!==null){await setBudget(range(year,month)[0],Number(v));load()}}}>Set / Edit</button></header><p>{budget?`${money(t.expenses)} of ${money(budget)} used • ${money(budget-t.expenses)} remaining`:'No budget set for this month.'}</p></section><section className="card"><h2>Calendar</h2><div className="calendar">{calendar.map(d=>{const date=`${year}-${String(month).padStart(2,'0')}-${String(d).padStart(2,'0')}`,count=tx.filter(x=>x.occurred_on===date||x.due_date===date).length;return <div key={d}><b>{d}</b>{count>0&&<small>{count} item{count>1?'s':''}</small>}</div>})}</div></section></>}
{page==='Expenses'&&<section className="card"><header><h2>Expenses</h2><button onClick={()=>open('expense')}>+ Add Expense</button></header>{rows(tx.filter(x=>x.kind==='expense'))}</section>}
{page==='Income & Savings'&&<><section className="metrics"><article><small>Monthly Income</small><b>{money(t.income)}</b></article><article><small>Monthly Savings</small><b>{money(t.savings)}</b></article><article><small>Savings Rate</small><b>{t.rate.toFixed(1)}%</b></article></section><section className="card"><header><h2>Income Sources</h2><button onClick={()=>open('income')}>+ Add Income</button></header>{rows(tx.filter(x=>x.kind==='income'))}</section><section className="card"><h2>Personal & Home Savings</h2>{(['Personal Savings','Home Savings'] as const).map(name=>{const g=goals.find(x=>x.name===name);return <div className="goal" key={name}><b>{name}</b><span>{money(g?.current_amount||0)}</span><button onClick={async()=>{const v=prompt(`${name} balance`,String(g?.current_amount||0));if(v!==null){await saveGoal({name,current_amount:Number(v),goal_amount:g?.goal_amount||0});load()}}}>Update</button></div>})}</section></>}
{page==='Reports'&&<Reports year={year} month={month}/>}
{page==='Settings'&&<section className="settings"><div className="card"><h2>Private on this device</h2><p>Your information stays in this browser/device. Export a backup regularly before changing phones or clearing browser data.</p></div><div className="card"><h2>App Theme</h2><button onClick={()=>setDark(!dark)}>{dark?'Use Light':'Use Dark'} Theme</button></div><div className="card"><h2>Data & Backup</h2><p>Export all local data to a JSON backup, then restore it later on this device.</p><button onClick={backup}>Export Backup</button><h3>Restore Backup</h3><RestoreBackup onDone={load}/><button className="danger" onClick={()=>{if(confirm('Reset all local finance data? This cannot be undone unless you have exported a backup.')){localStorage.removeItem('my-home-finance-personal-v1');load()}}}>Reset all local data</button></div></section>}
</main><nav className="mobileNav"><button onClick={()=>setPage('Dashboard')}>Dashboard</button><button onClick={()=>setPage('Expenses')}>Expenses</button><button className="add" onClick={()=>open('expense')}>＋</button><button onClick={()=>setPage('Income & Savings')}>Income & Savings</button><button onClick={()=>setPage('Settings')}>More</button></nav>{modal&&<TransactionModal kind={modal} initial={edit} onClose={()=>{setModal(null);setEdit(undefined)}} onSaved={load}/>}</div>}
function Reports({year,month}:{year:number;month:number}){const[busy,setBusy]=useState(false);async function monthly(){setBusy(true);try{const[s,e]=range(year,month),[r,b]=await Promise.all([listTransactions(s,e),getBudget(s)]);printHtml(monthlyReportHtml((r.data||[])as Transaction[],year,month,Number(b.data?.amount||0)))}finally{setBusy(false)}}async function yearly(){setBusy(true);try{const r=await listYear(year);printHtml(yearlyReportHtml((r.data||[])as Transaction[],year))}finally{setBusy(false)}}return <section className="card"><h2>Financial Reports</h2><p>Monthly is transaction-detailed. Yearly is a January–December closing summary without individual transactions.</p><div className="reportBtns"><button disabled={busy} onClick={monthly}>Monthly PDF / Print</button><button disabled={busy} onClick={yearly}>Yearly PDF / Print</button></div><small>Selected period: {month}/{year}</small></section>}
