import{FormEvent,useState}from'react';import{addTransaction,Transaction,updateTransaction}from'../lib/data';
const groups=['Home Expenses','Personal','Credit Card / Debt','Everyday / Misc'];const sources=['Salary','Bonus','Uber','Lyft','Freelance','Refund','Cash Income','Investment Income','Interest','Other Income'];
export default function TransactionModal({kind,initial,onClose,onSaved}:{kind:'income'|'expense';initial?:Transaction;onClose:()=>void;onSaved:()=>void}){
const[v,setV]=useState({occurred_on:initial?.occurred_on||new Date().toISOString().slice(0,10),name:initial?.name||'',amount:String(initial?.amount||''),group_name:initial?.group_name||'',category:initial?.category||'',merchant:initial?.merchant||'',status:initial?.status||'paid',payment_method:initial?.payment_method||'',due_date:initial?.due_date||'',notes:initial?.notes||''});const[msg,setMsg]=useState('');
async function save(e:FormEvent){e.preventDefault();if(!Number(v.amount)||Number(v.amount)<0)return setMsg('Enter an amount greater than zero.');const payload={...v,amount:Number(v.amount),kind,status:v.status as'paid'|'unpaid',group_name:v.group_name||null,category:v.category||null,merchant:v.merchant||null,due_date:v.due_date||null,payment_method:v.payment_method||null,notes:v.notes||null};const r=initial?await updateTransaction(initial.id,payload):await addTransaction(payload);if ('error' in r) {
    setMsg(r.error?.message ?? 'Unable to save transaction.');
} else {
    onSaved();
    onClose();
}}
return <div className="modal" role="dialog" aria-modal="true"><form className="modalCard" onSubmit={save}><header><h2>{initial?'Edit':'Add'} {kind==='income'?'Income':'Expense'}</h2><button type="button" onClick={onClose}>×</button></header><div className="formgrid"><label>Date<input type="date" required value={v.occurred_on} onChange={e=>setV({...v,occurred_on:e.target.value})}/></label><label>{kind==='income'?'Income source':'Expense name'}{kind==='income'?<><input list="income-sources" required value={v.name} placeholder="Salary or custom source" onChange={e=>setV({...v,name:e.target.value})}/><datalist id="income-sources">{sources.map(x=><option value={x} key={x}/>)}</datalist></>:<input required value={v.name} onChange={e=>setV({...v,name:e.target.value})}/>}</label><label>Amount<input type="number" min="0.01" step=".01" required value={v.amount} onChange={e=>setV({...v,amount:e.target.value})}/></label>{kind==='expense'&&<><label>Expense group<select required value={v.group_name} onChange={e=>setV({...v,group_name:e.target.value})}><option value="">Select</option>{groups.map(x=><option key={x}>{x}</option>)}</select></label><label>Category<input value={v.category} placeholder="e.g. Groceries" onChange={e=>setV({...v,category:e.target.value})}/></label><label>Status<select value={v.status} onChange={e=>setV({...v,status:e.target.value as 'paid'|'unpaid'})}><option value="paid">Paid</option><option value="unpaid">Unpaid</option></select></label><label>Due date<input type="date" value={v.due_date} onChange={e=>setV({...v,due_date:e.target.value})}/></label></>}<label>Payment method<input value={v.payment_method} onChange={e=>setV({...v,payment_method:e.target.value})}/></label><label className="wide">Notes<textarea value={v.notes} onChange={e=>setV({...v,notes:e.target.value})}/></label></div>{msg&&<p className="error">{msg}</p>}<button className="save">Save {kind==='income'?'Income':'Expense'}</button></form></div>}
